version: '3.9'
services:
  # client:
  #   build:
  #     context: ./apps/client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"

  # server:
  #   build:
  #     context: ./apps/server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3050:3050"
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./apps/server/dist:/app/dist
