name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy GCP Credentials File
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > ./application_default_credentials.json

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/DoRun-DoRun-nest.js
            git pull origin main --force
            sudo mv ./application_default_credentials.json /run/secrets/application_default_credentials.json
            sudo docker-compose pull
            sudo docker-compose up --build -d --remove-orphans
